name: co2-sisso
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - openpyxl
  - pyyaml
  - pre-commit
  - ruff
